version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"    
    volumes:
      - ./vector_db:/qdrant/storage
    restart: unless-stopped

  postgresql-main:
    platform: linux/amd64
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_server
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
      - ./server/sql:/mnt/sql

  redis_container:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"