version: '3.8'

# services:
#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant
#     ports:
#       - "6333:6333"    
#     volumes:
#       - /Users/been/Desktop/beenstudio/sandbox/poc_for_askku/qdrant_storage:/qdrant/storage
#     restart: unless-stopped

services:
  postgresql-main:
    platform: linux/amd64
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_server
    volumes:
      - /Users/been/Desktop/beenstudio/school/swe/database/postgresql:/var/lib/postgresql/data
      - /Users/been/Desktop/beenstudio/school/swe/server/sql:/mnt/sql

  redis_container:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6380:6379
    labels:
      - "name=redis"
      - "mode=standalone"